# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect)
from PySide6.QtGui import (QAction, QFont, QIcon)
from PySide6.QtWidgets import (QComboBox, QGridLayout, QHBoxLayout,
    QLabel, QLineEdit, QListView, QMenu, QMenuBar, QPushButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(528, 600)
        self.actionSaveConfig = QAction(MainWindow)
        self.actionSaveConfig.setObjectName(u"actionSaveConfig")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.actionSaveConfig.setIcon(icon)
        self.actionLoadConfig = QAction(MainWindow)
        self.actionLoadConfig.setObjectName(u"actionLoadConfig")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.actionLoadConfig.setIcon(icon1)
        self.actionShowLogs = QAction(MainWindow)
        self.actionShowLogs.setObjectName(u"actionShowLogs")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FormatJustifyLeft))
        self.actionShowLogs.setIcon(icon2)
        self.actionUnboundRecordToggle = QAction(MainWindow)
        self.actionUnboundRecordToggle.setObjectName(u"actionUnboundRecordToggle")
        self.actionUnboundRecordToggle.setCheckable(True)
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaRecord))
        self.actionUnboundRecordToggle.setIcon(icon3)
        self.actionSaveAs = QAction(MainWindow)
        self.actionSaveAs.setObjectName(u"actionSaveAs")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.actionSaveAs.setIcon(icon4)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.middle = QWidget(self.centralwidget)
        self.middle.setObjectName(u"middle")
        self.startRecordButton = QPushButton(self.middle)
        self.startRecordButton.setObjectName(u"startRecordButton")
        self.startRecordButton.setGeometry(QRect(20, 10, 210, 24))
        self.stopRecordButton = QPushButton(self.middle)
        self.stopRecordButton.setObjectName(u"stopRecordButton")
        self.stopRecordButton.setEnabled(True)
        self.stopRecordButton.setGeometry(QRect(20, 10, 211, 24))
        self.keyListView = QListView(self.middle)
        self.keyListView.setObjectName(u"keyListView")
        self.keyListView.setGeometry(QRect(20, 110, 210, 361))
        self.deleteKey = QPushButton(self.middle)
        self.deleteKey.setObjectName(u"deleteKey")
        self.deleteKey.setGeometry(QRect(20, 70, 210, 24))
        self.deleteAll = QPushButton(self.middle)
        self.deleteAll.setObjectName(u"deleteAll")
        self.deleteAll.setGeometry(QRect(20, 40, 210, 24))
        self.startRecordOutsideButton = QPushButton(self.middle)
        self.startRecordOutsideButton.setObjectName(u"startRecordOutsideButton")
        self.startRecordOutsideButton.setGeometry(QRect(20, 10, 211, 24))
        font = QFont()
        font.setBold(False)
        self.startRecordOutsideButton.setFont(font)
        self.stopRecordOutsideButton = QPushButton(self.middle)
        self.stopRecordOutsideButton.setObjectName(u"stopRecordOutsideButton")
        self.stopRecordOutsideButton.setEnabled(True)
        self.stopRecordOutsideButton.setGeometry(QRect(20, 10, 211, 24))
        self.appVersion = QLabel(self.middle)
        self.appVersion.setObjectName(u"appVersion")
        self.appVersion.setGeometry(QRect(10, 530, 231, 16))
        self.label_2 = QLabel(self.middle)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(260, 0, 141, 31))
        self.label_3 = QLabel(self.middle)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(260, 60, 131, 16))
        self.label = QLabel(self.middle)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 110, 171, 16))
        self.interval = QLineEdit(self.middle)
        self.interval.setObjectName(u"interval")
        self.interval.setGeometry(QRect(260, 30, 231, 24))
        self.limit = QLineEdit(self.middle)
        self.limit.setObjectName(u"limit")
        self.limit.setGeometry(QRect(260, 80, 231, 24))
        self.winNum = QComboBox(self.middle)
        self.winNum.setObjectName(u"winNum")
        self.winNum.setGeometry(QRect(260, 130, 231, 24))
        self.startButton = QPushButton(self.middle)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(270, 520, 121, 31))
        self.remainingTime = QLabel(self.middle)
        self.remainingTime.setObjectName(u"remainingTime")
        self.remainingTime.setGeometry(QRect(450, 500, 49, 16))
        self.stopButton = QPushButton(self.middle)
        self.stopButton.setObjectName(u"stopButton")
        self.stopButton.setGeometry(QRect(400, 520, 101, 31))
        self.stopRecordOutsideButton.raise_()
        self.startRecordOutsideButton.raise_()
        self.stopRecordButton.raise_()
        self.startRecordButton.raise_()
        self.keyListView.raise_()
        self.deleteKey.raise_()
        self.deleteAll.raise_()
        self.appVersion.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.interval.raise_()
        self.limit.raise_()
        self.winNum.raise_()
        self.startButton.raise_()
        self.remainingTime.raise_()
        self.stopButton.raise_()

        self.horizontalLayout.addWidget(self.middle)


        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 528, 21))
        self.menuParametres = QMenu(self.menubar)
        self.menuParametres.setObjectName(u"menuParametres")
        self.menuRecent = QMenu(self.menuParametres)
        self.menuRecent.setObjectName(u"menuRecent")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuParametres.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menuParametres.addAction(self.actionLoadConfig)
        self.menuParametres.addAction(self.actionSaveConfig)
        self.menuParametres.addAction(self.actionSaveAs)
        self.menuParametres.addAction(self.actionShowLogs)
        self.menuParametres.addAction(self.menuRecent.menuAction())
        self.menuOptions.addAction(self.actionUnboundRecordToggle)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionSaveConfig.setText(QCoreApplication.translate("MainWindow", u"Sauver", None))
#if QT_CONFIG(tooltip)
        self.actionSaveConfig.setToolTip(QCoreApplication.translate("MainWindow", u"Sauver la config", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoadConfig.setText(QCoreApplication.translate("MainWindow", u"Charger la config", None))
        self.actionShowLogs.setText(QCoreApplication.translate("MainWindow", u"Afficher le journal", None))
        self.actionUnboundRecordToggle.setText(QCoreApplication.translate("MainWindow", u"Enregistrer en dehors", None))
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"Enregister sous", None))
        self.startRecordButton.setText(QCoreApplication.translate("MainWindow", u"Demarrer l'enregistrement", None))
        self.stopRecordButton.setText(QCoreApplication.translate("MainWindow", u"Arreter l'enregistrement", None))
        self.deleteKey.setText(QCoreApplication.translate("MainWindow", u"Supprimer", None))
        self.deleteAll.setText(QCoreApplication.translate("MainWindow", u"Tout supprimer", None))
        self.startRecordOutsideButton.setText(QCoreApplication.translate("MainWindow", u"Demarrer l'enregistrement", None))
        self.stopRecordOutsideButton.setText(QCoreApplication.translate("MainWindow", u"Arreter l'enregistrement", None))
        self.appVersion.setText(QCoreApplication.translate("MainWindow", u"Version", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Intervale entre les touches", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Limite de temps (en m)", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Nombre de fenetres", None))
        self.interval.setText("")
        self.interval.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1 ou 1-5 pour aleatoire entre deux valeurs", None))
        self.limit.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.startButton.setText(QCoreApplication.translate("MainWindow", u"Depart", None))
        self.remainingTime.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.stopButton.setText(QCoreApplication.translate("MainWindow", u"Arret", None))
        self.menuParametres.setTitle(QCoreApplication.translate("MainWindow", u"Fichier", None))
        self.menuRecent.setTitle(QCoreApplication.translate("MainWindow", u"R\u00e9cents", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
    # retranslateUi
