name: Build NW Bot on Tag

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ['Run Pytest']
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate the python ui file
        run: pyside6-uic bot/ui/main_window.ui -o bot/ui/main_window.py
      - name: Build GUI executable
        run: |
          pyinstaller nwbot.spec
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/nwbot.exe
# TODO: generate the release notes
