name: unit tests

on: push

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --extra test

      - name: Generate UI file
        run: uv run pyside6-uic bot/ui/main_window.ui -o bot/ui/main_window_ui.py

      - name: Run tests with pytest
        run: uv run pytest

      - name: Coveralls
        uses: coverallsapp/github-action@v2

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --extra lint

      - name: Generate UI file
        run: uv run pyside6-uic bot/ui/main_window.ui -o bot/ui/main_window_ui.py

      - name: Run basedpyright
        run: uv run basedpyright

      - name: Run ruff
        run: uv run ruff check

  test-linux:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y xvfb libgl1 libegl1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --extra test

      - name: Generate UI file
        run: uv run pyside6-uic bot/ui/main_window.ui -o bot/ui/main_window_ui.py

      - name: Run tests with pytest
        run: xvfb-run -a uv run pytest

      - name: Coveralls
        uses: coverallsapp/github-action@v2
