name: unit tests

on: push

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Run tests with pytest
        run: python -m pytest

      - name: Coveralls
        uses: coverallsapp/github-action@v2

  test-linux:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y xvfb libgl1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Run tests with pytest
        run: xvfb-run -a python -m pytest

      - name: Coveralls
        uses: coverallsapp/github-action@v2
